### ISSUE TITLE
Add winner screen!

### ISSUE THREAD

**Issue by CarmenIJsebaart** [CarmenIJsebaart/DarkProject#6]

**Comment by JorikdeBoer** [comment]
There are now three scenario's with three different pictures:
Wolf eats RRH
Wolf eats Grandmother
RRH meets Grandmother

use the following code in main:

  sf::Texture wolfwins;
  wolfwins.loadFromFile("Wolf_winner_screen.png");
  sf::Sprite wolfwins_sprite(wolfwins);
  wolfwins_sprite.setPosition(0, 0);

  sf::Texture wolfwins2;
  wolfwins2.loadFromFile("deadgrandmother_winner_screen.png");
  sf::Sprite wolfwins2_sprite(wolfwins2);
  wolfwins2_sprite.setPosition(0, 0);

  sf::Texture RRHwins;
  RRHwins.loadFromFile("RRH_winner_screen.png");
  sf::Sprite RRHwins_sprite(RRHwins);
  RRHwins_sprite.setPosition(0, 0);

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

      else
      {
        state = Gamestate::game_won_by_wolf;
      }
      if(!has_to_die(GRANDMOTHER_sprite.getPosition(), WOLF_sprite.getPosition()))
      {
        w.draw(GRANDMOTHER_sprite);
      }
      else
      {
        state = Gamestate::dead_grandmother_wolf_wins;
      }
      if(!has_to_die(RRH_sprite.getPosition(), GRANDMOTHER_sprite.getPosition()))
      {
        w.draw(GRANDMOTHER_sprite);
      }
      else
      {
        state = Gamestate::game_won_by_RRH;
      }
      w.draw(WOLF_sprite);
      w.display();
    }
    if(state == Gamestate::game_won_by_wolf)
    {
      w.setView(view1);
      view1.setViewport(sf::FloatRect(0, 0, 1, 1));
      view1.setCenter(0, 0);
      wolfwins_sprite.setScale(0.4, 0.6);
      wolfwins_sprite.setPosition(-180, -175);
      w.clear(sf::Color::Red);
      w.draw(wolfwins_sprite);
      w.display();
    }
    if(state == Gamestate::dead_grandmother_wolf_wins)
    {
      w.setView(view1);
      view1.setViewport(sf::FloatRect(0, 0, 1, 1));
      view1.setCenter(0, 0);
      wolfwins2_sprite.setScale(0.4, 0.6);
      wolfwins2_sprite.setPosition(-170, -200);
      w.clear(sf::Color::Red);
      w.draw(wolfwins2_sprite);
      w.display();
    }
    if(state == Gamestate::game_won_by_RRH)
    {
      w.setView(view1);
      view1.setViewport(sf::FloatRect(0, 0, 1, 1));
      view1.setCenter(0, 0);
      RRHwins_sprite.setScale(0.55, 0.55);
      RRHwins_sprite.setPosition(-120, -120);
      w.clear(sf::Color::Red);
      w.draw(RRHwins_sprite);
      w.display();
    }
  }
}

**Comment by JorikdeBoer** [comment]
added new (temporary) gamestate, to be changed to include hunter scenario:
enum class Gamestate
  { running, game_won_by_RRH, game_won_by_wolf, dead_grandmother_wolf_wins };

**Comment by CarmenIJsebaart** [comment]
Done!
